version: 0.2
phases:
  pre_build:
    commands:
      - echo "Pre Build"
  build:
    commands:
      - echo "Building"
      - mvn clean compile war:war
  post_build:
    commands:
      - echo "Movendo Arquivos"
      - mv target/*.war ./ROOT.war
artifacts:
  files:
    - ROOT.war